"""
skills/builder/engine/contract_verifier.py - Symbolic Verification
===================================================================
System 2: AST-based verification of generated code against the OpenAPI spec.
Runs after each file is generated by the Coder, BEFORE writing to disk.
No LLM calls in verify_file_against_contract or build_ast_symbol_table.
"""

from __future__ import annotations

import ast
import os
import re
from typing import Any

from skills.builder.engine.context import blog


# ---------------------------------------------------------------------------
# Contract verification (NO LLM)
# ---------------------------------------------------------------------------
def verify_file_against_contract(
    file_path: str,
    file_content: str,
    openapi_spec: dict,
    subproject: str,
) -> list[dict]:
    """Analyze a generated file against the OpenAPI spec via AST/regex.

    Returns a list of violations (empty list = all ok).
    subproject: "backend" or "frontend"
    """
    if not openapi_spec or not openapi_spec.get("paths"):
        return []

    violations: list[dict] = []

    ext = os.path.splitext(file_path)[1].lower()

    try:
        if ext == ".py" and subproject == "backend":
            violations.extend(_verify_python_backend(file_path, file_content, openapi_spec))
        elif ext in (".js", ".mjs", ".jsx") and subproject == "frontend":
            violations.extend(_verify_js_frontend(file_path, file_content, openapi_spec))
        elif ext in (".ts", ".tsx", ".mts") and subproject == "frontend":
            violations.extend(_verify_ts_frontend(file_path, file_content, openapi_spec))
        elif ext in (".html", ".htm"):
            violations.extend(_verify_html(file_path, file_content, openapi_spec))
    except Exception as exc:
        blog.warning(f"Contract verification error for {file_path}: {exc}")

    return violations


def _verify_python_backend(
    file_path: str, content: str, spec: dict,
) -> list[dict]:
    """Verify Python backend file against OpenAPI spec using ast module."""
    violations: list[dict] = []

    # Collect spec endpoints
    spec_endpoints: dict[str, str] = {}  # path -> method
    spec_operation_ids: set[str] = set()
    for path, methods in spec.get("paths", {}).items():
        for method, operation in methods.items():
            if not isinstance(operation, dict):
                continue
            spec_endpoints[path] = method.upper()
            op_id = operation.get("operationId", "")
            if op_id:
                spec_operation_ids.add(op_id)

    # Parse AST
    try:
        tree = ast.parse(content)
    except SyntaxError:
        # Can't parse — skip contract verification, compile check will catch it
        return violations

    # Find all decorated route functions
    found_routes: dict[str, dict] = {}  # path -> {method, func_name, line}

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue

        for decorator in node.decorator_list:
            route_info = _extract_fastapi_route(decorator)
            if route_info:
                route_path, route_method = route_info
                found_routes[route_path] = {
                    "method": route_method,
                    "func_name": node.name,
                    "line": node.lineno,
                }

    if not found_routes:
        # Not a routes file, skip
        return violations

    # Check: all spec endpoints should be in found routes
    for spec_path, spec_method in spec_endpoints.items():
        matched = False
        for found_path in found_routes:
            if _paths_match(spec_path, found_path):
                matched = True
                found_method = found_routes[found_path]["method"]
                if found_method.upper() != spec_method.upper():
                    violations.append({
                        "severity": "error",
                        "type": "wrong_method",
                        "expected": f"{spec_method} {spec_path}",
                        "found": f"{found_method} {found_path}",
                        "line": found_routes[found_path]["line"],
                        "fix_hint": f"Change HTTP method from {found_method} to {spec_method} for {spec_path}",
                    })
                break

        if not matched:
            # Check if there's a route with similar path but different format
            similar = _find_similar_path(spec_path, list(found_routes.keys()))
            if similar:
                violations.append({
                    "severity": "error",
                    "type": "wrong_url",
                    "expected": spec_path,
                    "found": similar,
                    "line": found_routes[similar]["line"],
                    "fix_hint": f"Change route path from '{similar}' to '{spec_path}'",
                })

    # Check: no extra endpoints beyond spec
    for found_path, info in found_routes.items():
        found_in_spec = any(
            _paths_match(sp, found_path)
            for sp in spec_endpoints
        )
        if not found_in_spec:
            violations.append({
                "severity": "warning",
                "type": "extra_endpoint",
                "expected": "not in OpenAPI spec",
                "found": f"{info['method']} {found_path}",
                "line": info["line"],
                "fix_hint": f"Endpoint {info['method']} {found_path} is not in the OpenAPI spec. "
                            f"Either remove it or add it to the spec.",
            })

    # Check Pydantic models against spec schemas
    violations.extend(_verify_pydantic_models(tree, spec, content))

    return violations


def _extract_fastapi_route(decorator: ast.expr) -> tuple[str, str] | None:
    """Extract route path and method from a FastAPI decorator AST node."""
    # Handle @router.get("/path") or @app.get("/path")
    if isinstance(decorator, ast.Call):
        func = decorator.func
        if isinstance(func, ast.Attribute):
            method = func.attr.upper()
            if method in ("GET", "POST", "PUT", "DELETE", "PATCH"):
                if decorator.args:
                    arg = decorator.args[0]
                    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                        return arg.value, method
    return None


def _verify_pydantic_models(
    tree: ast.Module, spec: dict, content: str,
) -> list[dict]:
    """Verify Pydantic model fields against OpenAPI schema definitions."""
    violations: list[dict] = []

    # Collect component schemas
    schemas = spec.get("components", {}).get("schemas", {})
    if not schemas:
        return violations

    # Collect inline schemas from paths
    for path, methods in spec.get("paths", {}).items():
        for method, operation in methods.items():
            if not isinstance(operation, dict):
                continue
            op_id = operation.get("operationId", "")

            req_schema = (
                operation.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            if req_schema and req_schema.get("properties"):
                from skills.builder.engine.openapi_contract import _snake_to_pascal
                schemas[_snake_to_pascal(op_id) + "Request"] = req_schema

            resp_schema = (
                operation.get("responses", {})
                .get("200", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            if resp_schema and resp_schema.get("properties"):
                from skills.builder.engine.openapi_contract import _snake_to_pascal
                schemas[_snake_to_pascal(op_id) + "Response"] = resp_schema

    # Find class definitions that inherit from BaseModel
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue

        # Check if it inherits from BaseModel
        is_pydantic = any(
            (isinstance(b, ast.Name) and b.id == "BaseModel") or
            (isinstance(b, ast.Attribute) and b.attr == "BaseModel")
            for b in node.bases
        )
        if not is_pydantic:
            continue

        class_name = node.name

        # Find matching schema
        matching_schema = schemas.get(class_name)
        if not matching_schema:
            continue

        # Get class field names from AST
        class_fields: set[str] = set()
        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                class_fields.add(item.target.id)

        # Compare with spec fields
        spec_fields = set(matching_schema.get("properties", {}).keys())
        required_fields = set(matching_schema.get("required", []))

        # Missing required fields
        missing = required_fields - class_fields
        for field in missing:
            violations.append({
                "severity": "error",
                "type": "missing_field",
                "expected": f"Field '{field}' in model '{class_name}' (required by spec)",
                "found": f"Field not present",
                "line": node.lineno,
                "fix_hint": f"Add field '{field}' to class {class_name}",
            })

        # Wrong field names (case mismatch)
        for spec_field in spec_fields:
            if spec_field not in class_fields:
                # Check for camelCase/snake_case confusion
                camel = _to_camel_case(spec_field)
                snake = _to_snake_case(spec_field)
                for cf in class_fields:
                    if cf.lower() == spec_field.lower() or cf == camel or cf == snake:
                        violations.append({
                            "severity": "error",
                            "type": "wrong_field_name",
                            "expected": spec_field,
                            "found": cf,
                            "line": node.lineno,
                            "fix_hint": f"Rename field '{cf}' to '{spec_field}' in class {class_name}",
                        })

    return violations


def _verify_js_frontend(
    file_path: str, content: str, spec: dict,
) -> list[dict]:
    """Verify JavaScript frontend file against OpenAPI spec using regex."""
    violations: list[dict] = []

    # Collect spec endpoint paths and methods
    spec_paths: dict[str, str] = {}  # path -> method
    for path, methods in spec.get("paths", {}).items():
        for method in methods:
            if method.lower() in ("get", "post", "put", "delete", "patch"):
                spec_paths[path] = method.upper()

    if not spec_paths:
        return violations

    # Find all fetch() calls with URL patterns
    fetch_pattern = re.compile(
        r'''fetch\s*\(\s*[`'"](.*?)[`'"]'''
        r'''|fetch\s*\(\s*`\$\{[^}]+\}(.*?)`''',
        re.DOTALL,
    )

    for i, line in enumerate(content.splitlines(), 1):
        for match in fetch_pattern.finditer(line):
            url = match.group(1) or match.group(2) or ""
            # Normalize: strip API_BASE_URL prefix, template vars
            url = re.sub(r'\$\{[^}]*\}', '', url)
            url = url.strip()

            if not url or not url.startswith("/"):
                continue

            # Check if URL matches any spec path
            matched_spec_path = _find_matching_spec_path(url, spec_paths)
            if not matched_spec_path:
                # Possibly wrong URL
                similar = _find_similar_path(url, list(spec_paths.keys()))
                if similar:
                    violations.append({
                        "severity": "error",
                        "type": "wrong_url",
                        "expected": similar,
                        "found": url,
                        "line": i,
                        "fix_hint": f"Change fetch URL from '{url}' to '{similar}'",
                    })

        # Check HTTP method in fetch options
        method_match = re.search(
            r'''method\s*:\s*['"](GET|POST|PUT|DELETE|PATCH)['"]''',
            line, re.IGNORECASE,
        )
        if method_match:
            found_method = method_match.group(1).upper()
            # Find the nearest fetch URL above
            for j in range(max(0, i - 5), i):
                prev_line = content.splitlines()[j] if j < len(content.splitlines()) else ""
                url_match = fetch_pattern.search(prev_line)
                if url_match:
                    url = url_match.group(1) or url_match.group(2) or ""
                    url = re.sub(r'\$\{[^}]*\}', '', url).strip()
                    if url.startswith("/"):
                        matched_path = _find_matching_spec_path(url, spec_paths)
                        if matched_path and spec_paths.get(matched_path, "").upper() != found_method:
                            violations.append({
                                "severity": "error",
                                "type": "wrong_method",
                                "expected": f"{spec_paths[matched_path]} {matched_path}",
                                "found": f"{found_method} {url}",
                                "line": i,
                                "fix_hint": f"Change method from '{found_method}' to '{spec_paths[matched_path]}'",
                            })
                    break

    return violations


def _verify_ts_frontend(
    file_path: str, content: str, spec: dict,
) -> list[dict]:
    """TypeScript frontend verification — delegates to JS verifier (same regex logic)."""
    return _verify_js_frontend(file_path, content, spec)


def _verify_html(
    file_path: str, content: str, spec: dict,
) -> list[dict]:
    """Verify HTML file references."""
    violations: list[dict] = []

    # Check for hardcoded API URLs in inline scripts
    inline_scripts = re.findall(
        r'<script[^>]*>(.+?)</script>',
        content, re.DOTALL | re.IGNORECASE,
    )

    for script in inline_scripts:
        for match in re.finditer(r'''fetch\s*\(\s*['"]([^'"]+)['"]''', script):
            url = match.group(1)
            if url.startswith("/") and not url.startswith("//"):
                spec_paths = {
                    path: method
                    for path, methods in spec.get("paths", {}).items()
                    for method in methods
                    if method.lower() in ("get", "post", "put", "delete", "patch")
                }
                matched = _find_matching_spec_path(url, spec_paths)
                if not matched:
                    similar = _find_similar_path(url, list(spec_paths.keys()))
                    if similar:
                        violations.append({
                            "severity": "warning",
                            "type": "wrong_url",
                            "expected": similar,
                            "found": url,
                            "line": None,
                            "fix_hint": f"Inline script uses URL '{url}' but spec expects '{similar}'",
                        })

    return violations


# ---------------------------------------------------------------------------
# Contract verification loop (with LLM repair)
# ---------------------------------------------------------------------------
def run_contract_verification_loop(
    ws: dict,
    file_path: str,
    file_content: str,
    max_repair_attempts: int = 2,
    llm_call_fn=None,
    coder_model: str = "",
) -> str:
    """Verify a file against the contract and repair violations if found.

    Returns the (repaired or original) file content.
    """
    spec = ws.get("openapi_spec", {})
    if not spec or not spec.get("paths"):
        return file_content

    # Determine subproject
    path_lower = file_path.lower()
    if any(kw in path_lower for kw in ("backend", "server", "routes", "main.py", "app.py")):
        subproject = "backend"
    elif any(kw in path_lower for kw in ("frontend", "client", "api.js", "api.ts", ".html")):
        subproject = "frontend"
    else:
        return file_content  # Can't determine — skip

    violations = verify_file_against_contract(file_path, file_content, spec, subproject)

    if not violations:
        return file_content

    # Filter to errors only for repair
    errors = [v for v in violations if v["severity"] == "error"]
    warnings = [v for v in violations if v["severity"] == "warning"]

    # Log all violations
    ws.setdefault("contract_violations", []).extend(violations)

    for w in warnings:
        blog.warning(
            f"Contract warning in {file_path}: {w['type']} "
            f"(expected: {w['expected']}, found: {w['found']})"
        )

    if not errors:
        return file_content  # Only warnings — don't repair

    blog.warning(f"Contract verification: {len(errors)} error(s) in {file_path}")
    for v in errors[:5]:
        blog.warning(f"  [{v['type']}] expected: {v['expected']}, found: {v['found']}")

    if not llm_call_fn:
        return file_content

    # Repair loop
    from skills.builder.engine.context import strip_fences, _code_hash

    current_content = file_content
    seen_hashes = {_code_hash(current_content)}

    # Extract relevant spec sections for context
    relevant_spec = _extract_relevant_spec(spec, violations)

    for attempt in range(1, max_repair_attempts + 1):
        blog.repair(file_path, attempt, max_repair_attempts)

        violation_desc = "\n".join(
            f"  - [{v['type']}] Line {v.get('line', '?')}: "
            f"expected '{v['expected']}', found '{v['found']}'. "
            f"Fix: {v['fix_hint']}"
            for v in errors
        )

        repair_prompt = f"""Fix the following CONTRACT VIOLATIONS in this file.
The file must match the OpenAPI specification exactly.

FILE: {file_path}

VIOLATIONS:
{violation_desc}

RELEVANT OPENAPI SPEC:
{json.dumps(relevant_spec, indent=2, default=str)[:4000]}

CURRENT CODE:
{current_content}

RULES:
  1. Fix ONLY the violations listed above
  2. DO NOT change any other code
  3. DO NOT modify function signatures unless the fix requires it
  4. URL paths, HTTP methods, and field names must match the spec EXACTLY
  5. Output ONLY the corrected code, no fences, no explanation"""

        try:
            response = llm_call_fn(
                model=coder_model,
                prompt=repair_prompt,
                system="Expert developer. Fix API contract violations. Output ONLY code.",
                max_tokens=14336,
                temperature=0.05,
            )
            repaired = strip_fences(response)

            # Stagnation detection
            h = _code_hash(repaired)
            if h in seen_hashes:
                blog.warning(f"Contract repair stagnated for {file_path} after {attempt} attempts")
                break
            seen_hashes.add(h)

            # Re-verify
            new_violations = verify_file_against_contract(file_path, repaired, spec, subproject)
            new_errors = [v for v in new_violations if v["severity"] == "error"]

            if not new_errors:
                blog.info(f"Contract violations fixed in {file_path}")
                return repaired

            current_content = repaired
            errors = new_errors
            blog.warning(f"Contract repair attempt {attempt}: {len(new_errors)} errors remain")

        except Exception as exc:
            blog.warning(f"Contract repair failed for {file_path}: {exc}")
            break

    return current_content


import json


def _extract_relevant_spec(spec: dict, violations: list[dict]) -> dict:
    """Extract only the paths referenced in violations."""
    relevant: dict[str, Any] = {"paths": {}}

    # Collect all URLs mentioned in violations
    mentioned_urls: set[str] = set()
    for v in violations:
        for field in ("expected", "found"):
            val = v.get(field, "")
            # Extract path-like strings
            for part in val.split():
                if part.startswith("/"):
                    mentioned_urls.add(part)

    # If no specific URLs, include all paths
    if not mentioned_urls:
        relevant["paths"] = spec.get("paths", {})
        return relevant

    for spec_path in spec.get("paths", {}):
        for url in mentioned_urls:
            if _paths_match(spec_path, url) or _paths_match(url, spec_path):
                relevant["paths"][spec_path] = spec["paths"][spec_path]
                break

    # Include schemas used in matched paths
    if spec.get("components", {}).get("schemas"):
        relevant["components"] = {"schemas": spec["components"]["schemas"]}

    return relevant


# ---------------------------------------------------------------------------
# AST Symbol Table (NO LLM)
# ---------------------------------------------------------------------------
def build_ast_symbol_table(written_files: dict) -> dict:
    """Build a symbol table from all written files for cross-file awareness.

    Returns:
    {
        "functions": {"function_name": "defined_in_file.py"},
        "classes": {"ClassName": "defined_in_file.py"},
        "endpoints": {"/api/path": {"method": "POST", "defined_in": "routes.py"}},
        "exports": {"export_name": "defined_in_file.js"}
    }
    """
    table: dict[str, dict] = {
        "functions": {},
        "classes": {},
        "endpoints": {},
        "exports": {},
    }

    for fpath, content in written_files.items():
        ext = os.path.splitext(fpath)[1].lower()

        if ext == ".py":
            _extract_python_symbols(fpath, content, table)
        elif ext in (".js", ".mjs", ".jsx", ".ts", ".tsx", ".mts"):
            _extract_js_symbols(fpath, content, table)

    return table


def _extract_python_symbols(fpath: str, content: str, table: dict) -> None:
    """Extract Python symbols using AST."""
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            table["functions"][node.name] = fpath

            # Check for route decorators
            for dec in node.decorator_list:
                route_info = _extract_fastapi_route(dec)
                if route_info:
                    path, method = route_info
                    table["endpoints"][path] = {
                        "method": method,
                        "defined_in": fpath,
                    }

        elif isinstance(node, ast.ClassDef):
            table["classes"][node.name] = fpath


def _extract_js_symbols(fpath: str, content: str, table: dict) -> None:
    """Extract JavaScript/TypeScript symbols using regex."""
    # Functions
    for match in re.finditer(r'(?:function|async\s+function)\s+(\w+)\s*\(', content):
        table["functions"][match.group(1)] = fpath

    # Arrow functions assigned to const
    for match in re.finditer(r'(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?\(', content):
        table["functions"][match.group(1)] = fpath

    # Classes
    for match in re.finditer(r'class\s+(\w+)', content):
        table["classes"][match.group(1)] = fpath

    # Exports
    for match in re.finditer(r'export\s+(?:default\s+)?(?:function|class|const|let|var)\s+(\w+)', content):
        table["exports"][match.group(1)] = fpath

    # module.exports
    for match in re.finditer(r'module\.exports\s*=\s*\{([^}]+)\}', content):
        for name in re.findall(r'(\w+)', match.group(1)):
            table["exports"][name] = fpath

    # Express/router routes
    for match in re.finditer(
        r'''(?:router|app)\.(get|post|put|delete|patch)\s*\(\s*['"]([^'"]+)['"]''',
        content, re.IGNORECASE,
    ):
        method = match.group(1).upper()
        path = match.group(2)
        table["endpoints"][path] = {"method": method, "defined_in": fpath}


def format_symbol_table_for_prompt(symbol_table: dict) -> str:
    """Format the symbol table as context for the Coder LLM."""
    if not any(symbol_table.values()):
        return ""

    lines = ["=== ALREADY DEFINED (DO NOT REDEFINE) ==="]

    if symbol_table.get("endpoints"):
        lines.append("\nAPI Endpoints:")
        for path, info in symbol_table["endpoints"].items():
            lines.append(f"  {info['method']} {path} (in {info['defined_in']})")

    if symbol_table.get("functions"):
        lines.append("\nFunctions:")
        for name, fpath in list(symbol_table["functions"].items())[:30]:
            lines.append(f"  {name}() — defined in {fpath}")

    if symbol_table.get("classes"):
        lines.append("\nClasses:")
        for name, fpath in symbol_table["classes"].items():
            lines.append(f"  {name} — defined in {fpath}")

    if symbol_table.get("exports"):
        lines.append("\nExports:")
        for name, fpath in list(symbol_table["exports"].items())[:20]:
            lines.append(f"  {name} — from {fpath}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Path matching helpers
# ---------------------------------------------------------------------------
def _paths_match(spec_path: str, code_path: str) -> bool:
    """Check if two URL paths match, treating {param} as wildcards."""
    spec_parts = spec_path.strip("/").split("/")
    code_parts = code_path.strip("/").split("/")

    if len(spec_parts) != len(code_parts):
        return False

    for sp, cp in zip(spec_parts, code_parts):
        # Path params
        if sp.startswith("{") and sp.endswith("}"):
            continue
        if cp.startswith("{") and cp.endswith("}"):
            continue
        if cp.startswith(":"):
            continue  # Express-style :param
        if sp.lower() != cp.lower():
            return False

    return True


def _find_similar_path(target: str, candidates: list[str]) -> str | None:
    """Find the most similar path from candidates using simple heuristics."""
    target_parts = target.strip("/").split("/")

    best_match = None
    best_score = 0

    for candidate in candidates:
        cand_parts = candidate.strip("/").split("/")

        # Count matching segments
        score = 0
        min_len = min(len(target_parts), len(cand_parts))
        for i in range(min_len):
            tp = target_parts[i]
            cp = cand_parts[i]
            if tp == cp:
                score += 2
            elif tp.lower() == cp.lower():
                score += 1
            elif tp.startswith("{") or cp.startswith("{") or cp.startswith(":"):
                score += 1

        # Penalize length mismatch
        score -= abs(len(target_parts) - len(cand_parts))

        if score > best_score:
            best_score = score
            best_match = candidate

    # Only return if score is above threshold
    if best_score >= len(target_parts):
        return best_match
    return None


def _find_matching_spec_path(url: str, spec_paths: dict[str, str]) -> str | None:
    """Find the matching spec path for a URL."""
    for spec_path in spec_paths:
        if _paths_match(spec_path, url):
            return spec_path
    return None


def _to_camel_case(name: str) -> str:
    """Convert snake_case to camelCase."""
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _to_snake_case(name: str) -> str:
    """Convert camelCase to snake_case."""
    result = re.sub(r'([A-Z])', r'_\1', name).lower()
    return result.lstrip("_")
